FROM tensorflow/tensorflow:2.9.1

WORKDIR /app

COPY model_training_export_and_load.py .

CMD ["python", "-c", "import model_training_export_and_load; model_training_export_and_load.create_compile_fit_save_model()"]
